name: 04 - Workflow uses actions
on: 
    workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-lates
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Pokaz zawartość
              run: ls -la



                 